language: node_js
node_js:
  - 13

install:
  - npm i
  - npx lerna bootstrap

script:
  - npx lerna run lint
  - npx lerna run test
  - npx lerna run build

after_script:
  - npx lerna run benchmark
  - npx lerna run semantic-release